### ISSUE TITLE
Strict differentiation of predefined and custom buildings

### ISSUE THREAD

**Issue by FroggieFrog** [AgmasGold/anno-designer#106]
This issue emerged after a private discussion with @StingMcRay on discord according to issue #105.

We came to the conclusion that there is a need for a strict(er) differentiation of `buildings from the presets file` and `custom buildings created by the user` that are not in the presets file.

The intention of the logic used in issue #105 was to check if a building with the same settings that the user made (icon and size) is found in the presets file and "map" the custom building to a predefined one.
This is somewhat hacky and not very transparent to the user.

**So the following idea emerged:**
If a building from the presets file is selected (via TreeView) then there will be a green border around the building settings.
If the user "created" a custom building then there will be an orange border.
Maybe a checkbox or something where the user "accepts" the automatic conversion.

The use of different borders would make it more transparent to the user that the building configuration is not in the presets file.
Also to avoid countless `"Unknown Building"` entries in the statistics the label entered by the user could be used.

**This is a quick mockup:**
![unknown](https://user-images.githubusercontent.com/6222752/58827475-6a8bfa00-8643-11e9-91e3-f4bd902d75d9.png)

So the next thing is to define which setting should be used to find a building in the presets file.
Continue to use the current logic of `same icon` and `same size` (rotation doesn't matter) or use some other logic?

Please share your opinions! It is an open discusison.

**Comment by StingMcRay** [comment]
This Issue was addressed in Anno Designer version 9 i believe, however it is not mentioned, but will fixed now in PR #356 
The only way an "Unknown Object" in statistics screen is showed, if the user make a building at start and not name it on the label text box. 
Name change can be done, on known buildings and own creation without selected a preset tree building, as long users fill in the Label, however those buildings will never be translated for others, as they are not part of the preset list.

**Comment by FroggieFrog** [comment]
The root problem for opening this issue might be solved, but the idea of this PR is still not solved.

Currently (and also after PR #356) there is no way for a user to know if a building is from the presets or a custom building.

**Comment by StingMcRay** [comment]
I know, we need to dive in deeper in this matter... i have some ideas but need to work that out on my mind first
